name: IaC Recertification

on:
  schedule:
    - cron: '0 2 * * 0' # Weekly on Sunday at 2am
  workflow_dispatch:

jobs:
  recertify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Build ICE
      run: go build -o ice ./cmd/ice
      
    - name: Run Recertification
      run: ./ice run
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        # Config is assumed to be in .ice.yaml or passed via flag
